### ISSUE TITLE
Transfer all Categories/Hindi.html links to Databases/Hindi.json

### ISSUE THREAD

**Issue by n-ce** [n-ce/YTFLIX#27]
- Format is pre-specified
- Further Instructions are given in first object of Anime.json

**Comment by abhishekalekar** [comment]
[Hindi.zip](https://github.com/n-ce/YTFLIX/files/7083660/Hindi.zip)
Please find the attached zip file includes convert Hindi.html to Hindi.json as format specified in Anime.json

**Comment by n-ce** [comment]
> [Hindi.zip](https://github.com/n-ce/YTFLIX/files/7083660/Hindi.zip)
> Please find the attached zip file includes convert Hindi.html to Hindi.json as format specified in Anime.json

Thanks a lot, @abhishekalekar I have merged your changes but I would still love to add your contribution to this project, considering opening a pull request with your name edited at the contributing part of Readme.md
