### ISSUE TITLE
Add More Categories : Contents of other languages

### ISSUE THREAD

**Issue by n-ce** [n-ce/YTFLIX#34]
Improve/Add to the Database
Create new category, namely a language.
To create a new category, create a new json file in the database folder and populate the file with links. [Other contribution details](https://github.com/n-ce/YTFLIX/blob/main/CONTRIBUTING.md) 
Example Languages :
- Korean
- French
- Spanish

**Comment by ryanwillyams** [comment]
I made a pull request. Can assign this to me?

**Comment by n-ce** [comment]
@ryanwillyams thanks for the new Korean database! 
However we need to incorporate new code in html and script so that the database actually gets connected, are you up for that?
