### ISSUE TITLE
Grid View in Landscape

### ISSUE THREAD

**Issue by n-ce** [n-ce/YTFLIX#39]
Currently The categories are streched horizontally in desktop or landscape mode, reduce the size of the cards in landscape & Introduce Grid View in landscape to make it responsive for users.

**Comment by sanjana-98** [comment]
Hi @n-ce . Can I work on this.

**Comment by n-ce** [comment]
Yes, Thank you. Just Make sure not to change anything about the existing mobile view.

**Comment by sanjana-98** [comment]
Ok

**Comment by n-ce** [comment]
I'm so sorry, one of our team members already came up with the grid, so now I have to close this. Again, Thank you for Showing your Support. Do look at the project and tell us how we could improve it by creating a new issue.
