### ISSUE TITLE
Add more youtube links of movies/series to the database

### ISSUE THREAD

**Issue by n-ce** [n-ce/YTFLIX#43]
Adding more Links to the Database.
### Requirements
- It should be either a movie or series
- It should be a youtube video
- Links can be added without any authorisarion, check out how to contribute [here.](https://github.com/n-ce/YTFLIX/blob/main/CONTRIBUTING.md)

**Comment by the-amazing-atharva** [comment]
Just added a movie (no. 48) in the Hindi section of the Wiki 
Was the format correct?

**Comment by n-ce** [comment]
> Just added a movie (no. 48) in the Hindi section of the Wiki Was the format correct?
- I checked and its correct.
- alternatively, To verify if the format works, the best way is to open up the site and check the links there.
- Thanks for the contribution!
